name: Prod Polybot Service Deployment

on:
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_APP_URL: ${{ secrets.TELEGRAM_APP_URL_PROD }}
  EC2_HOST: ${{ secrets.EC2_HOST_PROD }}
  EC2_USER: ${{ secrets.EC2_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart bot
          EOF
<<<<<<< HEAD
=======

>>>>>>> dde27fd07d2199523d788f8645fdb9f17ee50ee4
